openapi: 3.0.4
info:
  title: Text Language
  description: Text Language is a simple tool for detecting the language of a text. It returns the language code.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/textlanguage:
    post:
      summary: Detect Language
      description: Text Language is a simple tool for detecting the language of a text. It returns the language code.
      operationId: textlanguage
      parameters: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  language: french
                  iso: fr
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The text to detect the language of
                  example: Ceci est un exemple de texte. Il peut détecter la langue
              required:
              - text
              example:
                text: Ceci est un exemple de texte. Il peut détecter la langue
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
